class Util {
    static CLEAR_MESSAGE = "CLEAR_MESSAGE";
    static ADD_MESSAGE = "ADD_MESSAGE"
    static UPDATE_MESSAGE = "UPDATE_MESSAGE"
    static DELETE_MESSAGE = "DELETE_MESSAGE"
    static TOGGLE_POPUP = "TOGGLE_POPUP"
    static UPDATE_MESSAGE_TYPE = "UPDATE_MESSAGE_TYPE"
    static UPDATE_TEXT_BOX = "UPDATE_TEXT_BOX"
}

export default Util